---

- name: Install prerequisites packages
  become: true
  ansible.builtin.apt:
    name: python3-pip
    update_cache: true

- name: Install prerequisites python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "--user --break-system-packages --no-cache-dir --no-build-isolation"
  loop:
    - Cython<3
    - pyyaml==5.4.1
    - docker
    - docker-compose
    - requests

- name: Reset connection so docker group is picked up.
  ansible.builtin.meta: reset_connection
