---

- name: Install prerequisites packages
  become: true
  ansible.builtin.apt:
    name: python3-pip
    update_cache: true

- name: Install prerequisites python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: --user
  loop:
    - docker==6.1.3
    - docker-compose

- name: Reset connection so docker group is picked up.
  ansible.builtin.meta: reset_connection
