---
- name: Restart docker compose
  community.docker.docker_compose_v2:
      project_src: "{{ docker_compose_default_path }}/{{ docker_compose_project_name }}"
      use_ssh_client: true
      restarted: true
