---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    libvirt
platforms:
  - name: ansible-role-docker-compose-jammy
    box: generic/ubuntu2204
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
